/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Auth$Params as Auth$Params } from './fn/login/auth';
export { auth as auth } from './fn/login/auth';
export type { UserGetall$Params as UserGetall$Params } from './fn/user/user-getall';
export { userGetall as userGetall } from './fn/user/user-getall';
export type { UserInsert$Params as UserInsert$Params } from './fn/user/user-insert';
export { userInsert as userInsert } from './fn/user/user-insert';
export type { UpdateStatus$Params as UpdateStatus$Params } from './fn/user/update-status';
export { updateStatus as updateStatus } from './fn/user/update-status';
export type { ProductGetall$Params as ProductGetall$Params } from './fn/product/product-getall';
export { productGetall as productGetall } from './fn/product/product-getall';
export type { ProductInsert$Params as ProductInsert$Params } from './fn/product/product-insert';
export { productInsert as productInsert } from './fn/product/product-insert';
export type { CategoryGetall$Params as CategoryGetall$Params } from './fn/category/category-getall';
export { categoryGetall as categoryGetall } from './fn/category/category-getall';
export type { CategoryInsert$Params as CategoryInsert$Params } from './fn/category/category-insert';
export { categoryInsert as categoryInsert } from './fn/category/category-insert';
export type { LaboratoryGetall$Params as LaboratoryGetall$Params } from './fn/laboratory/laboratory-getall';
export { laboratoryGetall as laboratoryGetall } from './fn/laboratory/laboratory-getall';
export type { LaboratoryInsert$Params as LaboratoryInsert$Params } from './fn/laboratory/laboratory-insert';
export { laboratoryInsert as laboratoryInsert } from './fn/laboratory/laboratory-insert';
export type { InventoryGetall$Params as InventoryGetall$Params } from './fn/inventory/inventory-getall';
export { inventoryGetall as inventoryGetall } from './fn/inventory/inventory-getall';
export type { LotGetall$Params as LotGetall$Params } from './fn/lot/lot-getall';
export { lotGetall as lotGetall } from './fn/lot/lot-getall';
