/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ProductInsert$Params {
      body?: {
'barcode'?: string;
'description'?: string;
'idCategory'?: string;
'idLaboratory'?: string;
'image'?: string;
'name'?: string;
'nextExpiration'?: string;
'priceSale'?: string;
'requiresPrescription'?: string;
'stockMinimum'?: string;
'totalStock'?: string;
}
}

export function productInsert(http: HttpClient, rootUrl: string, params?: ProductInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, productInsert.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

productInsert.PATH = '/products/insert';
