/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SaleInsert$Params {
      body?: {
'discount'?: number;
'idCustomer'?: string;
'idUser'?: string;
'items'?: Array<{
'idLot'?: string;
'idProduct'?: string;
'quantity'?: number;
'unitPrice'?: number;
}>;
'paymentMethod'?: string;
}
}

export function saleInsert(http: HttpClient, rootUrl: string, params?: SaleInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, saleInsert.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

saleInsert.PATH = '/sale/save';
